/*
 * TACTILE_SWITCH_config.h
 *
 *  Created on: Feb 25, 2016
 *      Author: Anwar
 */

#ifndef TACTILE_SWITCH_CONFIG_H_
#define TACTILE_SWITCH_CONFIG_H_



#endif /* TACTILE_SWITCH_CONFIG_H_ */

/*Comment: this diver supports only 8 switches*/

#define TACTILE_u8SWITCHNUMBER 1

#define TACTILE_u8SWITCH1TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH2TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH3TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH4TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH5TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH6TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH7TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH8TYPE TACTILE_u8ACTIVEHIGH


#define TACTILE_u8SWITCH9TYPE  TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH10TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH11TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH12TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH13TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH14TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH15TYPE TACTILE_u8ACTIVEHIGH
#define TACTILE_u8SWITCH16TYPE TACTILE_u8ACTIVEHIGH


#define TACTILE_u8SWITCH1PIN DIO_u8PIN31
#define TACTILE_u8SWITCH2PIN DIO_u8PIN0
#define TACTILE_u8SWITCH3PIN DIO_u8PIN0
#define TACTILE_u8SWITCH4PIN DIO_u8PIN0
#define TACTILE_u8SWITCH5PIN DIO_u8PIN0
#define TACTILE_u8SWITCH6PIN DIO_u8PIN0
#define TACTILE_u8SWITCH7PIN DIO_u8PIN0
#define TACTILE_u8SWITCH8PIN DIO_u8PIN0


#define TACTILE_u8SWITCH9PIN  DIO_u8PIN0
#define TACTILE_u8SWITCH10PIN DIO_u8PIN0
#define TACTILE_u8SWITCH11PIN DIO_u8PIN0
#define TACTILE_u8SWITCH12PIN DIO_u8PIN0
#define TACTILE_u8SWITCH13PIN DIO_u8PIN0
#define TACTILE_u8SWITCH14PIN DIO_u8PIN0
#define TACTILE_u8SWITCH15PIN DIO_u8PIN0
#define TACTILE_u8SWITCH16PIN DIO_u8PIN0





