/*
 * TACTILE_SWITCH_private.h
 *
 *  Created on: Feb 25, 2016
 *      Author: Anwar
 */

#ifndef TACTILE_SWITCH_PRIVATE_H_
#define TACTILE_SWITCH_PRIVATE_H_

#define TACTILE_u8SWITCHSTATERELEASED 0
#define TACTILE_u8SWITCHSTATEDEBOUNCING 1
#define TACTILE_u8SWITCHSTATEPRESSED 2



#define TACTILE_u8ZEROLOOPINDX 0
#define TACTILE_u8COUNTINITVAL 0

#define TACTILE_MAXSWITCH 16

#define MAX_COUNT 10
#endif /* TACTILE_SWITCH_PRIVATE_H_ */
